dist: trusty
sudo: false
language: python
python: 3.6
cache:
  apt: true
  pip: true
install:
  - pip install -U ucca
  - python -m spacy download en_core_web_md
env:
  global:
    - SCRIPTS=https://raw.githubusercontent.com/UniversalConceptualCognitiveAnnotation/docs/master/scripts
    - secure: "u13WyfKKnOfCcHLubAL8cSYVrDUd7YPkRSePxEICUyMZijhyO2WLNWwqjBcXuwr+9ZLq8fRtDOXOCy7ep9ljUbgXkWYTA9xg1f6vaAXPHEWGokBD9EI+dHk/kN/D2a9OCBl04841nYyeNB5Rie6MukfX9gQJKoWpfp+DDQf+gsUqYY5WNuwNFWgFkPJLUpryezfcaHauu6FVV0UJ9SDJfsidaIlzJ7ssibl9RgzFnSC90SCMd2kN/5FFw1DtwrV6uff1D5o5boF1UXY6kxHSM8HHY/A4gYIeX4WsmJdjxuSw9jTmEj9Cd0m5n+Du5PprNCkFq26WRPxYsUWlOHBiSZvGOX4UyEtsn1ndGuQ2gui+dNKCGhfIEhjqQSZjaqw32z4zDNa60KhL7BviTXnyGuZAfDZLRlZKn2TgtssTTcYchA1Z5lqJrzNK9edzDaYYgUe20u96bPxwKXhH4l4rjhEC/jQSn7wv2XdfrQbbeA4HznTTYU+221E/YZZza7bfdLFunHR0pLGxTqCa7/LH3lsW7yR0pswNWYY1teRlqSVyK1/qWqVVMEQlHEaE4/7212HTXIvGSlEjxbZDboxRP1hUdVwl9t5wv+GSfOYxCtBstGufO3cBDJNUm8KJfDcDCDsDaWZy+/vMDqdIIrt6msNXEs2CFdU9G8FUbT59z7E="
jobs:
  include:
    - script: python -m scripts.validate --no-linkage xml
    - stage: split
      script:
        - scripts/get_ud.sh
        - rm -rf UD_English-EWT ud ud.txt
        - curl $SCRIPTS/split_to_sentences.sh | bash -s sentences_by_ud
      env: ucca
    - script:
        - scripts/get_ud.sh
        - rm -rf UD_English-EWT sentences_by_ud ud.txt
        - scripts/branch_ud.sh
      env: ud
    - stage: convert
      script: curl $SCRIPTS/validate_sentences.sh | bash -s -- || echo Ignoring validation failures
      env: FORMAT=validate
    - script: curl $SCRIPTS/sentences_to_xml.sh | bash
      env: FORMAT=xml
    - script: curl $SCRIPTS/tupa.sh | bash
      env: FORMAT=tupa
    - script: curl $SCRIPTS/visualize.sh | bash -s "[0-1]"
      env: FORMAT=visualize
    - script: curl $SCRIPTS/visualize.sh | bash -s "[2-9]"
      env: FORMAT=visualize
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=sdp
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=conll
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=conllu
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=amr
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=export
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=txt
    - stage: evaluate
      script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=sdp
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=conll
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=conllu
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=amr
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=export
after_success: curl $SCRIPTS/push.sh | bash

